language: java
jdk:
  - oraclejdk8

sudo: required
dist: trusty

services:
  - mongodb
  - docker

addons:
  apt:
    packages:
    - sshpass

cache:
  directories:
  - $HOME/.m2

env:
  global:
  - TERM=dumb
  - secure: "PN4iKva7zaGiZHMO/GFh+VGXgD2j06iBfJOJOacFrgV8bk3LHYYVpdRjil3KwxtsfqlNNMt6ME+lVT20GFjFWCjluCN4VV8H2ookXIhdM0MzTDz/VyWSicN4Sp5AjI417o+zBe28+u0I6g+tq+lutATzfZzmMaRdh81beMRr6O+bSbjQWKcV7OQOTFgMOR/2vahZwTjnclwGZaTOqumvuHbhdDi9Y0LKyx7B5FD9sxZ+eTwlRjRSMlyjJA7Fqc+XDxhxGdom4kKdW8Ag7t0StjnkUqSKWggsQxWxKB0qYSgCa8g6IRDG+v+78yqLPAf2YJy+bC/1SpHWbjcQozqCTd0O91P5D4OcXnXs732mfkkvmGwgLlycpCy7wcgmIqrkc3FspY2cH1JHJz3t5dFefaWGqHUNMPFWFd4cU2cKmYumgmGEXQqSLR9ZKIvm4vLpSRZAvwkArmTUN3v6G7soZyihEXuaLk9RfD6QNihy0Eds3m+ffhcIUxvGHc4x4ej6ChmBEU2ViUJ+LHFwmhFpAYiDrsJjgCQMCac6CVsOZsh7IFksSR/fPRglelU/krbdkQVKof0CdH87OsMZPAgzrRXPr5Yak+007yzu5eEVDcG4gX1WYJIwkF0/5BLF8dL6EC3HDEMcDNhvXFnvB3LTEbCSCaXd6pUHDaR6z4d0wyU=" #DOCKER_USER
  - secure: "nJfk/lPzXyKRQcKc47zkX7jHz+yzc0cnjXZ0mhdETOx97U9WHI4MVWfWmijXjsZp1rUWtVdTl0qrbMWb+dYRLMJ45KqPkU+89mwDpk7wayi7TeYfjwgxFbDloTZ1kv7UxcDi+p/7FxIlqxcPy7G4TczLcPHEAlCOjBFge0SFxNX3QMJPeqX4iNyhd54/rMyL7s6+acwYLIalWFtPemcFYgddRBkAgydWbCzcMs1L+tzPszJUmYkTpmWJRcnopj9j54cXnMafeCC2ZXTJWfszmJlQsSdcCjY+msrKCg5vW6RhK4Jlt8menty5YH+XpgCTMFgQ52SsH9eoqTmpCIAIvPWwM7iJ03vdRTN10r4gbUv8+BgQ80OpUudD4Q5cIj7HgiPp6kALvaM0UDvpHQM7+ccxUwf0rfQXtWb6DRp9xjO8n+jrFS+DQ8zlPDzX1QaqQVnl4vMh2hm4xqFlfR7aSUhIimqqCGJS7Rjb8FrmbZ50L23rVeINT0Pb00TfOAUpa/tf8DO8nrt1rsDOzU7cBYv5xtTi1dn7XTgn5QBTBnNlw/ApZcq7q36KQLHwOgdLgWG+WuAMPCMXRyxXC8ggZ68cxtwBVXeH6BJgMGcu3bzGsU5hz9TeyDsY98KL1wcBSKrs3Yddba8QzNtHYd3/XKD4ERtQ0mAPGpg4uTRl4yA=" #DOCKER_PASS
  - secure: "KDgk5y1UdIgahFxSb2yUiEPI37/lQibYxtADLFlbB0nyLFFmZgRXYo50MsWNNt4Ws+9H0a+0j4et+HQLh3G4Lyv6bIw7k6Kc1aO55p4zxNv+3sc0vhg4CjCIGd61AJ+18huWbes7DNXL4elJJ5PSkRXp4IIY9nOpGk20vhjph1j67SgjGRVVN2ndo5YebJhAZ5SC7hlllzmMusc135WWFCF8EEkzOtmdQLfYhWQWDQ4dQGp7TGn7lGWB/ns56jbgGEOYhybmobMWVULd9WJJ44fZWAzPL/rp6EZebd62e2hBmLT7NlpqLNvmJ6FjBcYbnbj0JxSAdrjVLGtDsWOixTVJJeeXuKlYCQ/JDtJ/krbvJhML5jkSs2i3O1cqi1rFpaRjy1I4l/slrppRghI2Ymp/UzbjZttIT8yMxSSle4rYpbodX2aX8mM5Ecac218wDqvXKZjVwpdnNB0GJYGVhCR9s2un+p5GKE0Lwru+hKyUJanADyo6Qbod+I/5SqIdv/bzWezjHrbDL6ZW5DqdRf0DugQa1jMEYWiB5bTtvKwVYRXseO5Q+HvFyIU6Hc8EovLkMKv8wnZMwXff60Fay/mbovlcHz8b/ULRspV9166T+va5fkGsLlkTM57t9l3elBSXDMelSg6Orl/iqFFfQGGUprJeGCnmS7C2pRKCGqw=" #DEPLOY_HOST
  - secure: "ThI+TwfAm0yTQ2mcxAOlDn7fQF8Qwq7EB0LZV6T0bq4pxC+2+K6emcNgErMMhTjwZanZHqpAUPpOFmlVk3c0IQHe1GqXcGJcwqHCyzYLzH7x0j9RcYQiVppbn/djl6ULUDUyeFG650SP7uVFp+2fnEkoVjJBu5Am5ghpRuwlYm0DvNdxJkiCrsFb8bIMgnGFvkmcnCK5c5BidDhBUM99vC4h0X1R7lHMN2LzPCLtEiKTVOKWcxLle+9bII2SYlH5b4Pe1SE0iwNU3yuLWDdOzjNKCiX0VXRs7fre2Yk+u3xrHtoP2swjiV1/U/EOplOXagxDpLf/XoYXhwGdIj5oz2KpIMq9m750d/R0leZD/NRUb5QUTsq2T/CxKCyXebYBWi3o2L8X99JhEt61I7if1OhiD5OLWKDI890EcNaaU10VPrt8TreFYjX580cpcdPqyM1zAQE6RzLRYEL3WZmOmo4ttG30I/Eo4RJN/Sf3u1ISUHJmuHqHZIfQOZlgcQha6Ls7cUxv+sfV/CMvzGY5PJdNVelUwZshgkehHZGYz+BX0HMzMw1CKhzuemNgtD7wSQWJj7VcguszqIwaJyIbO+kfRLQ7b7V7VP2kWNzQBad9Xq/g4ls36uqS1+Phfqi6RgLcr+8mjJVlRVBX/HLWk8mbKn8x03Vy3mJwYOcYl6I=" #DEPLOY_PATH
  - secure: "ub5CwZqE3nmZF/QDy18NSzLwYl9ciGB4vM2s6Qjc4JWg/fIaKcU1pl2fsyRY1fqJSYU8Z4kmVslH3sHAdDv4SLog1I3mrovpHBWIUPlA1kFYHmGGv1hsRg84vE/ywoxtXl+ZGvR43TMTlxID0olzG1zYGSWdHxwpHWqmqcxX9BjUOTz6LQoZuoMpsIQNnKCiy2M8g5U4Mpzi2+VYGuvgWyBGdFSGtsavuzD8ReKJM77ow1VRfY2FNJ/SALotVz860iYrspB/0fuyN7nz4Eco1+A8BE7kwXfbVYd02k/X/vHs2KXyy83x5fAJxJ3YatxVfGByr4kgWbcjdiQySCKSKLpAt81i7OoPfxQ2cvPfNK6EGUHbvvHlH4KS2Y+NLJaVv0/ifAgFmkdJeuw4fDXa7oiA2GsPdxDslUl0+QQGHBSY2055MVAwE8gjTF0GVw6PpdxB7rQS5F8qqAJeri9DT9XOHhnAjUsCRuw2VmWH90FoxVKtL6ldWcv3AYDoHSyXYMVjjIslvJCOCrZnr+iIeMovlXSyF61w0U+GhI75bK+nlFXIhn+I2vReonUIImRGtYb8UpUS9ph0qlia+F8Qbd5sKeuOB2hkCM44RAH6CbT/epo7UbyqRD2zg/sGboVrOqZKg0hfgjZ5NVRur9pQxyR5nlMNZhFTVF0um9yHRe8=" #DEPLOY_USER
  - secure: "TUeYoDMZ2FO7L1L/rhlA99lz+7em9U2EXAE43X6WUrybJmBmGNB7Nv1URu1J458xqoTKNAqszMy4FiXgO0ZYM8/13WnH8v0ioq0rEUM7kZDZ2iq2osSzVwguMf01KCRQjt4cVc5Q5xB5nLmL24KsiVku6slKKOwaVKtJaLBH2NfQV5W+x6YvZ8FuWofXmYHeZndI3C0KFCKuUjNp5Ldv4hP8VLrXiW7Hp5F77uUJQudavg7GanpbztjeX835HNYCoX1ykiIOpknFG28A25MRBGZC40FFXv/WiEdNoqoeCQmaHfD2+OlcRtOVu0w09ZPUfHz+lmU2XQP8q8l17yQoodxKrhqpO+1GbByStFdNMAoBz3DKon9Yja5YcV6ITJk8Grh1xSRbQO6GPrgb94xk557lu9mrVZ4wSLVRS7RqwvLCnrY5PWIRGQIWXUX3TWVXDFMjkCufO/rplPhXJleIuib+DhjPw3SeRsSjCz3uqa57SEmniugVVbd7ME03oxKvb4gt9GbeavydIhfXHC65E+2larwdJhulUq2v3qZlmEkMDav2OCQk6jynS8DX9n4xq9zXs/lD5WP6O5r/fBZoim4wwvYCmokWZjvd1aQ5HsBUH39BDGODIXkHiqcUNXuu2t2T9aZ7pjfsesulbjny6tgZGvB2BnQb75LMxtDrhS0=" #DEPLOY_PASS
  - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - sudo -H pip install --upgrade pip setuptools
  - sudo -H pip install -r frontend/webapp/src/main/webapp/requirements.txt;

script:
  - mvn clean install;
  - sudo python frontend/webapp/src/main/webapp/runtests.py;

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH != "master" && exit
  - mvn install -DskipTests=true -Pdocker
  - echo "test"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
# docker push api
  - export API_REPO=seppaleinen/worldinmovies-api
  - docker tag $API_REPO $API_REPO:$TAG
  - docker tag $API_REPO $API_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $API_REPO
# docker push webapp
  - export WEBAPP_REPO=seppaleinen/worldinmovies-webapp
  - docker tag $WEBAPP_REPO $WEBAPP_REPO:$TAG
  - docker tag $WEBAPP_REPO $WEBAPP_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $WEBAPP_REPO
# ssh into server and run deployscript
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && git pull && docker-compose kill; docker ps -a | grep -v 'data' | awk '{print $1}' | xargs docker rm -f; docker-compose pull && docker-compose up -d --build && docker images -qf 'dangling=true' | xargs docker rmi -f"