language: java
jdk:
  - oraclejdk8

sudo: required
dist: trusty

services:
  - docker

addons:
  apt:
    packages:
    - sshpass

cache:
  directories:
  - $HOME/.m2

env:
  global:
  - TERM=dumb
  - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - sudo -H pip install --upgrade pip setuptools
  - sudo -H pip install -r frontend/webapp/src/main/webapp/requirements.txt;

script:
  - mvn clean install;
  - sudo python frontend/webapp/src/main/webapp/runtests.py;
