language: java
jdk:
- oraclejdk8

sudo: required
group: edge
dist: trusty

services:
  - mongodb
  - docker

addons:
  apt:
    packages:
    - sshpass

cache:
  directories:
  - $HOME/.m2

env:
  global:
  - TERM=dumb
  - secure: "hFzsx5R1Rn20FwF+szY3WLaE2BcnqTHfwfmWrGgaXLcbyiRgrW0tc2oS6lRiaMk+yll2asJuWuoOj8pUB3/hNtV1wIMmXopBTh6tajhFB18Eq/w0E4Cfm2auq0RLd+VY4RSGTI1VYDdwiEqFvCUp6yZG1OFkXGhycN14YkiWxbler8S8ajnSE2fYBeDDQW/bkx+rEyBWSttvzAIs/6Ep3KOXueXALXA1yUD7HyG2EEHerl2F0cUCKelyfPgr5RN0gnAZHboBWBYAT4IHKMd1mpY5QI9kHzrql/pl00xD2lVjh2K06VMImKbiZXbZiV7kznBeV1S9QvCMTZkTSataGhkKJJ/gONlM1tnEXqHyXdn++XUlHcs5yvObrixQ1LYpIDa1P0WIqkNXDGPuT6sn+qKzz6IiCUSmlhGiU5or2n3ahpwN2ZiRSm/S2lV6VvQggfT246EVfuLh/YI7oQiPbUhIQwHHYEjyQ9DiwYPXt59CU1YYbdo2CAQvwNJ1lLa/x77yR6MTnagFI9Hd/V43nzs7nI9lN3Wl6JlCY2w5cOO8B5W0t1R8fc3G1eyjNMH9vgc15Iy/c1pknexzzHY0FW1+BRpiJqXDYDV32TcVVlVXm0m87mQx8u7n3gRY282XMvWQiJe5+jdQC/SIBBHXqQm4QfvDANHTT/AUeyEt1PE=" #DOCKER_USER
  - secure: "SY+mGR4k8nhDiTwrMClqVhv5WjqkohEvrXyHQiQhXy1NvYjM1FlWJ2OLCOLObCAidyyfNgVgItf3z+kUpXNStVkIhppnr+uaNsUz2ZKCGPVEp7CDW28LK1b6lPxZzBDYx4V69Ofa0j5Qcn5VTB4FaFWYIrjLICOoL3zdfB8kKlyyN2tPjrB2V+vnAjqFMwVXY6Zik3HZOVcBeAWOCwI7fSfCvA6kTDzz8CV45BwDyXKki8QG0g4Y7ZwW131MUhIbi+DyRjWBj56aq30wRurtajwnpVR8Onn2TEb3U7ARV4nQxFoVrM1obFUMEHbnUChJcvn7I/Wv7IY+WWhXTxQubQsvPhw1sWgghw13irSMfA8y37QpRGm9k8uZZ0PF6Qe7nBGPHSu+3MDJzzPC11F0+lE/FJtuEUxHH2GhBr7BfLS2qlAsqOav7ApS864JJaECjSvNpwFycVpb6p9E7rc/eIxPkPkg2hjBGDboOKsDYF7D4mdBEihAZpGLehy5ATW5Ksteaxc+7GFhyLmftwtq5RKI921/bH/kfrz81XHUlF0vUK2yYaUxFrb/iHjOZBHR/CnAV2X8j4kSHz0wmShwce+Ov98lz/2V05li27taIYfYEca5kks76XuvxfC3XFYaSH+6ewdrGMR/URUuz3Y3ipe/rgqqq3EWILcg+jEobQI=" #DOCKER_PASS
  - secure: "KDgk5y1UdIgahFxSb2yUiEPI37/lQibYxtADLFlbB0nyLFFmZgRXYo50MsWNNt4Ws+9H0a+0j4et+HQLh3G4Lyv6bIw7k6Kc1aO55p4zxNv+3sc0vhg4CjCIGd61AJ+18huWbes7DNXL4elJJ5PSkRXp4IIY9nOpGk20vhjph1j67SgjGRVVN2ndo5YebJhAZ5SC7hlllzmMusc135WWFCF8EEkzOtmdQLfYhWQWDQ4dQGp7TGn7lGWB/ns56jbgGEOYhybmobMWVULd9WJJ44fZWAzPL/rp6EZebd62e2hBmLT7NlpqLNvmJ6FjBcYbnbj0JxSAdrjVLGtDsWOixTVJJeeXuKlYCQ/JDtJ/krbvJhML5jkSs2i3O1cqi1rFpaRjy1I4l/slrppRghI2Ymp/UzbjZttIT8yMxSSle4rYpbodX2aX8mM5Ecac218wDqvXKZjVwpdnNB0GJYGVhCR9s2un+p5GKE0Lwru+hKyUJanADyo6Qbod+I/5SqIdv/bzWezjHrbDL6ZW5DqdRf0DugQa1jMEYWiB5bTtvKwVYRXseO5Q+HvFyIU6Hc8EovLkMKv8wnZMwXff60Fay/mbovlcHz8b/ULRspV9166T+va5fkGsLlkTM57t9l3elBSXDMelSg6Orl/iqFFfQGGUprJeGCnmS7C2pRKCGqw=" #DEPLOY_HOST
  - secure: "ThI+TwfAm0yTQ2mcxAOlDn7fQF8Qwq7EB0LZV6T0bq4pxC+2+K6emcNgErMMhTjwZanZHqpAUPpOFmlVk3c0IQHe1GqXcGJcwqHCyzYLzH7x0j9RcYQiVppbn/djl6ULUDUyeFG650SP7uVFp+2fnEkoVjJBu5Am5ghpRuwlYm0DvNdxJkiCrsFb8bIMgnGFvkmcnCK5c5BidDhBUM99vC4h0X1R7lHMN2LzPCLtEiKTVOKWcxLle+9bII2SYlH5b4Pe1SE0iwNU3yuLWDdOzjNKCiX0VXRs7fre2Yk+u3xrHtoP2swjiV1/U/EOplOXagxDpLf/XoYXhwGdIj5oz2KpIMq9m750d/R0leZD/NRUb5QUTsq2T/CxKCyXebYBWi3o2L8X99JhEt61I7if1OhiD5OLWKDI890EcNaaU10VPrt8TreFYjX580cpcdPqyM1zAQE6RzLRYEL3WZmOmo4ttG30I/Eo4RJN/Sf3u1ISUHJmuHqHZIfQOZlgcQha6Ls7cUxv+sfV/CMvzGY5PJdNVelUwZshgkehHZGYz+BX0HMzMw1CKhzuemNgtD7wSQWJj7VcguszqIwaJyIbO+kfRLQ7b7V7VP2kWNzQBad9Xq/g4ls36uqS1+Phfqi6RgLcr+8mjJVlRVBX/HLWk8mbKn8x03Vy3mJwYOcYl6I=" #DEPLOY_PATH
  - secure: "ub5CwZqE3nmZF/QDy18NSzLwYl9ciGB4vM2s6Qjc4JWg/fIaKcU1pl2fsyRY1fqJSYU8Z4kmVslH3sHAdDv4SLog1I3mrovpHBWIUPlA1kFYHmGGv1hsRg84vE/ywoxtXl+ZGvR43TMTlxID0olzG1zYGSWdHxwpHWqmqcxX9BjUOTz6LQoZuoMpsIQNnKCiy2M8g5U4Mpzi2+VYGuvgWyBGdFSGtsavuzD8ReKJM77ow1VRfY2FNJ/SALotVz860iYrspB/0fuyN7nz4Eco1+A8BE7kwXfbVYd02k/X/vHs2KXyy83x5fAJxJ3YatxVfGByr4kgWbcjdiQySCKSKLpAt81i7OoPfxQ2cvPfNK6EGUHbvvHlH4KS2Y+NLJaVv0/ifAgFmkdJeuw4fDXa7oiA2GsPdxDslUl0+QQGHBSY2055MVAwE8gjTF0GVw6PpdxB7rQS5F8qqAJeri9DT9XOHhnAjUsCRuw2VmWH90FoxVKtL6ldWcv3AYDoHSyXYMVjjIslvJCOCrZnr+iIeMovlXSyF61w0U+GhI75bK+nlFXIhn+I2vReonUIImRGtYb8UpUS9ph0qlia+F8Qbd5sKeuOB2hkCM44RAH6CbT/epo7UbyqRD2zg/sGboVrOqZKg0hfgjZ5NVRur9pQxyR5nlMNZhFTVF0um9yHRe8=" #DEPLOY_USER
  - secure: "O+IHCVM824YoNLgxb7jCPR+q2zefqeFsKC/2oFsxDsb+dOoNy1oeeopDofEQknthgahJWrjlt+ClsfrrMRnOqLeUyphuMZfLIH4uMXZKtl8JuB4GI44MUbFik5YRWVl9zsIZyeGVT5uDyQjfH4M40ULWbUXw/PJiKeYgK6oQW3d6rwb2oUTKR/KCJousECGNuuj/pkACMwl/fBig1c0gaqqQdl7M60rKl2LkK5Klt2x6jkojt7ec5eojbJnv/ybt8CAA8Z3+BHJL+JjbLMqhGZidx4RRijuHHgXl4NXQe9czQpe457EFPxqLvs6wdITfkPYWoxkzDwjTyT5x0irHRXLXVXr2oc+1gSP8g+NaUwHg/Q6TFgmzVf/yJYX8JdDK1xtPfwQyTq4UKFy0vwGuZ038DL/NdYF79U3vGYmFe0iILKgt/t0zz5GjfsREM7fMxP3Clt5iUnQJRDivAPp4sDfbOAgnp+Hui06uo59rJ+CKA+7lhGipbBFp/Re0jN/iVnKYRBa2GAivBieb9WJYG4rXaL6ikTkSgC4OJ9D+D0JrtpzGs9y1ualBKpNh4vpZsReaK3HgZujCEdGz/L6WmP79Mg8WssQ53qFkumuxF7wErRPUJQ8e2UxvwYIEjEd8UY2PTzcry6BZO+AET58CDWkMVJCHpFqFxf30mxCZY4U=" #DEPLOY_PASS
  - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - sudo -H pip install --upgrade pip setuptools
  - sudo -H pip install -r frontend/webapp/src/main/webapp/requirements.txt;

script:
  - mvn clean install;
  - sudo python frontend/webapp/src/main/webapp/runtests.py;

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH != "master" && exit
  - mvn install -DskipTests=true -Pdocker
  - echo "test"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
# docker push api
  - export API_REPO=seppaleinen/worldinmovies-api
  - docker tag $API_REPO $API_REPO:$TAG
  - docker tag $API_REPO $API_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $API_REPO
# docker push batch
  - export BATCH_REPO=seppaleinen/worldinmovies-batch
  - docker tag $BATCH_REPO $BATCH_REPO:$TAG
  - docker tag $BATCH_REPO $BATCH_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $BATCH_REPO
# docker push webapp
  - export WEBAPP_REPO=seppaleinen/worldinmovies-webapp
  - docker tag $WEBAPP_REPO $WEBAPP_REPO:$TAG
  - docker tag $WEBAPP_REPO $WEBAPP_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $WEBAPP_REPO
# ssh into server and run deployscript
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && git pull && docker-compose kill; docker ps -a | grep -Ev 'data|mongo' | awk '{print $1}' | xargs docker rm -f; docker-compose pull && docker-compose build && docker-compose up -d && docker images -qf 'dangling=true' | xargs docker rmi -f"