version: "2"

services:
  nginx:
    restart: always
    build: frontend/nginx/src/main
    image: seppaleinen/worldinmovies-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /www/static
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/letsencrypt-auto:/tmp/letsencrypt-auto
      - /opt/nginx:/opt/nginx
    volumes_from:
      - web
    links:
      - web:web

  web:
    restart: always
    image: seppaleinen/worldinmovies-webapp
    expose:
      - "8000"
    links:
      - api:api
    depends_on:
      - api
    volumes:
      - /webapp/application/static
    command: gunicorn --config=gunicorn.config.py wsgi:app

  api:
    image: seppaleinen/worldinmovies-api
    restart: always
    links:
     - mongo
    depends_on:
     - mongo

  batch:
    image: seppaleinen/worldinmovies-batch
    restart: never
    links:
     - mongo
    depends_on:
     - mongo

  mongo:
    image: mongo
    restart: always
    volumes_from:
     - data

  data:
    image: mongo
    restart: never
    volumes:
      - /data/db
    command: echo ''
