frontend:
  image: seppaleinen/worldinmovies-frontend
  ports:
   - "80:80"
  links:
   - backend
backend:
  image: seppaleinen/worldinmovies-backend
  links:
   - mongo
mongo:
  image: seppaleinen/worldinmovies-database