frontend:
  image: seppaleinen/worldinmovies-frontend
  restart: always
  ports:
   - "80:80"
  links:
   - backend
backend:
  image: seppaleinen/worldinmovies-backend
  restart: always
  ports:
   - "10080:10080"
  links:
   - mongo
mongo:
  image: seppaleinen/worldinmovies-database