frontend:
  image: seppaleinen/worldinmovies-frontend
  ports:
   - "4000:4000"
  links:
   - backend
backend:
  image: seppaleinen/worldinmovies-backend
  ports:
   - "10080:10080"
  links:
   - mongo
mongo:
  image: seppaleinen/worldinmovies-database
  ports:
   - "27017:27017"