version: '2.3'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql
      - ./postgres-data:/tmp/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  backend:
    image: seppaleinen/worldinmovies_backend
    build: backend/
    expose:
      - 8000
    depends_on:
      - db
    restart: on-failure
    environment:
      - TMDB_API=${TMDB_API}
      - SENTRY_URL=${SENTRY_URL}
    volumes:
      - gunicornsocket:/run/

  webapp:
    image: seppaleinen/worldinmovies_webapp
    build: frontend/app/
    depends_on:
      - backend
    ports:
      - "81:80"
    volumes:
      - gunicornsocket:/run/
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-http://localhost:81}
      - REACT_APP_SENTRY_URL=${SENTRY_URL_FRONTEND}

volumes:
  pgdata:
  gunicornsocket:
