version: '3.3'

services:
  traefik:
    image: traefik:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Give access to all containers to traefik
      - ./traefik/traefik.toml:/traefik.toml # Basic config file
      - ./traefik/acme.json:/acme.json # Stores the Let’s Encrypt certificate date
    networks:
      - web
  db:
    image: postgres:10.5-alpine
    volumes:
      - pgdata:/var/lib/postgresql
      - ./postgres-data:/tmp/
    ports:
      - "5433:5432"
    networks:
      - internal
    labels:
      - "traefik.enable=false"
  backend:
    image: worldinmovies_backend
    build: backend/
    volumes:
      - ./backend/:/code
    expose:
      - "8000"
    depends_on:
      - db
    restart: always
    environment:
      - TMDB_API=${TMDB_API}
      - SENTRY_URL=${SENTRY_URL}
    networks:
      - web
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.backend=backend"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:backend.${DOMAIN:-localhost}"
      - "traefik.port=8000"
  webapp:
    image: worldinmovies_webapp
    build: frontend/app/
    ports:
      - "81:80"
    depends_on:
      - backend
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:frontend.localhost"
      - "traefik.backend=webapp"
      - "traefik.port=80"
volumes:
  pgdata:
networks:
  internal:
  web:
    external: true
