version: '2.3'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql
      - ./postgres-data:/tmp/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  backend:
    image: seppaleinen/worldinmovies_backend
    build: backend/
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    environment:
      - TMDB_API=${TMDB_API}
      - SENTRY_URL=${SENTRY_URL}
  webapp:
    image: seppaleinen/worldinmovies_webapp
    build: frontend/app/
    ports:
      - "81:80"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
      - REACT_APP_SENTRY_URL=${SENTRY_URL_FRONTEND}
volumes:
  pgdata:
