frontend:
  image: seppaleinen/worldinmovies-frontend
  restart: always
  ports:
   - "80:80"
  links:
   - backend
backend:
  image: seppaleinen/worldinmovies-backend
  restart: always
  links:
   - mongo
  expose:
   - "10080"
mongo:
  image: seppaleinen/worldinmovies-database
  expose:
   - "27017"