version: '3.8'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql
      - ./postgres-data:/tmp/
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 20s
      timeout: 60s
      retries: 5
      start_period: 3s

  mongo:
    image: mongo:jammy
    volumes:
      - "mongo_data:/data/db"
    ports:
      - "27017:27017"

  tmdb_import:
    image: seppaleinen/worldinmovies_tmdb_import
    build: backend/tmdb_import/
    ports:
      - "8020:8020"
    environment:
      - TMDB_API=${TMDB_API}
    depends_on:
      - mongo
      - kafka

  kafka:
    image: docker.io/bitnami/kafka:3.4
    privileged: true
    ports:
      - "2181:2181"
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_BROKER_ID=1001
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1001@127.0.0.1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  backend:
    image: seppaleinen/worldinmovies_backend
    build: backend/base/
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
    environment:
      - TMDB_API=${TMDB_API}
      - SENTRY_URL=${SENTRY_URL}
    volumes:
      - gunicornsocket:/run/
    healthcheck:
      test: curl -sSLf http://localhost/health -LsS -f >/dev/null || exit 1
      interval: 60s
      timeout: 30s
      retries: 2
      start_period: 5s

  webapp:
    image: seppaleinen/worldinmovies_webapp
    build: frontend/app/
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - gunicornsocket:/run/
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-http://localhost:81}
      - REACT_APP_SENTRY_URL=${SENTRY_URL_FRONTEND}
    healthcheck:
      test: ['CMD', 'nc', '-vz', '-w1', 'localhost', '443']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  #certbot:
  #  image: certbot/certbot
  #  entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  pgdata:
  gunicornsocket:
  certs:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongo_data:
    driver: local
