nginx:
  restart: always
  image: seppaleinen/worldinmovies-nginx
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

web:
  restart: always
  image: seppaleinen/worldinmovies-webapp
  expose:
    - "8000"
  links:
    - api:api
  volumes:
    - /usr/src/app/application/static
  command: gunicorn --config=gunicorn.config.py wsgi:app

api:
  image: seppaleinen/worldinmovies-api
  restart: always
  links:
   - mongo

batch:
  image: seppaleinen/worldinmovies-batch
  restart: never
  links:
   - mongo

mongo:
  image: mongo
  restart: always
  volumes_from:
   - data

data:
  image: mongo
  restart: always
  volumes:
    - /data/db
  command: echo ''
