version: '3'

services:
  db:
    image: postgres:10.5-alpine
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5433:5432"
  web:
    image: worldinmovies_backend
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    environment:
      - TMDB_API=${TMDB_API}
      - SENTRY_URL=${SENTRY_URL}
volumes:
  pgdata: