# Generated by Django 4.1.5 on 2023-01-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_alternativetitle_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativetitle',
            name='iso_3166_1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='alternativetitle',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_titles', to='app.movie'),
        ),
    ]
