# Generated by Django 4.1.5 on 2023-03-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_remove_movie_raw_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="weighted_rating",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
