# Generated by Django 4.2.6 on 2023-10-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0029_change_raw_response_from_dict_to_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternativetitle",
            name="title",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="alternativetitle",
            name="type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_id",
            field=models.CharField(
                db_index=True, max_length=30, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="original_title",
            field=models.CharField(max_length=1000),
        ),
    ]
