# Generated by Django 4.2.6 on 2023-10-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0030_alter_alternativetitle_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="imdb_vote_average",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_vote_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="vote_average",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="movie",
            name="vote_count",
            field=models.IntegerField(default=0),
        ),
    ]
