# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app.proto.movies_pb2 as movies__pb2


class MoviesControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMovies = channel.stream_stream(
                '/movies.MoviesController/GetMovies',
                request_serializer=movies__pb2.GetMoviesRequest.SerializeToString,
                response_deserializer=movies__pb2.Movie.FromString,
                )


class MoviesControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMovies(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MoviesControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMovies': grpc.stream_stream_rpc_method_handler(
                    servicer.GetMovies,
                    request_deserializer=movies__pb2.GetMoviesRequest.FromString,
                    response_serializer=movies__pb2.Movie.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movies.MoviesController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MoviesController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMovies(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/movies.MoviesController/GetMovies',
            movies__pb2.GetMoviesRequest.SerializeToString,
            movies__pb2.Movie.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
