# Generated by Django 2.2.3 on 2019-07-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movie',
        ),
    ]
