# Generated by Django 2.2.3 on 2019-07-20 11:07

from django.db import models, migrations, connection


def migrate_production_countries(apps, schema_editor):
    Movie = apps.get_model('app', 'Movie')
    ProductionCountries = apps.get_model('app', 'ProductionCountries')

    for movie in Movie.objects.filter(fetched=True).all():
        for country in movie.production_countries.all():
            try:
                prod_country = ProductionCountries.objects.filter(iso_3166_1=country.iso_3166_1).first()
            except Exception as exc:
                prod_country = country
                prod_country.save()
            movie.production_countries2.add(prod_country)
    # Remove all unused prod_countries
    with connection.cursor() as cursor:
        cursor.execute("delete from app_productioncountries "
                       "where id not in (select productioncountries_id from app_productioncountries_movies)")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190720_1305'),
    ]

    operations = [
        migrations.RunPython(migrate_production_countries),
    ]
