# Generated by Django 2.2.3 on 2019-07-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190720_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativetitle',
            name='type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
