# Generated by Django 2.2.3 on 2019-09-12 10:11

from django.db import migrations, connection


def delete_duplicate_imdb_ids(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("update app_movie set imdb_id = null where imdb_id = '';")

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_duplicate_imdb_ids'),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_imdb_ids),
    ]
