# Generated by Django 2.2.3 on 2019-09-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_set_all_empty_imdb_ids_to_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(db_index=True, max_length=30, null=True, unique=True),
        ),
    ]
