version: "2"

services:
  selenium:
    restart: never
    build: .
    links:
     - nginx:nginx
    depends_on:
     - nginx

  nginx:
    restart: always
    build: ../frontend/nginx/src/main
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /www/static
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/letsencrypt-auto:/tmp/letsencrypt-auto
      - /opt/nginx:/opt/nginx
    volumes_from:
      - web
    links:
      - web:web

  web:
    restart: always
    image: seppaleinen/worldinmovies-webapp
    expose:
      - "8000"
    environment:
      - BACKEND_URL=http://api:10080
      - SENTRY_DSN=https://34ce8ef3cc3740339cac1d70afae7d54:33f2eb87d7d8446cab3564f87d2be8fb@sentry.io/100439
      - SENTRY_RELEASE=0.0.1
    links:
      - api:api
    depends_on:
      - api
    volumes:
      - /webapp/application/static
    command: gunicorn --config=gunicorn.config.py wsgi:app

  api:
    image: seppaleinen/worldinmovies-api
    restart: always
    ports:
      - "10080:10080"
    environment:
      - SENTRY_DSN=https://34ce8ef3cc3740339cac1d70afae7d54:33f2eb87d7d8446cab3564f87d2be8fb@sentry.io/100439
      - SENTRY_RELEASE=0.0.1
    links:
     - mongo
    depends_on:
     - mongo

  mongo:
    image: mvertes/alpine-mongo
    restart: always
    volumes_from:
     - data

  data:
    image: mvertes/alpine-mongo
    restart: never
    volumes:
      - /data/db
    command: echo ''
