# Generated by Django 2.2.3 on 2019-07-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('original_title', models.CharField(max_length=200)),
                ('popularity', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
