# Generated by Django 2.2.3 on 2019-07-16 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('original_title', models.CharField(max_length=500)),
                ('popularity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fetched', models.BooleanField(default=False)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=30, null=True)),
                ('original_language', models.CharField(blank=True, max_length=30, null=True)),
                ('overview', models.CharField(blank=True, max_length=2000, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=40, null=True)),
                ('release_date', models.CharField(blank=True, max_length=10, null=True)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('raw_response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_1', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spoken_languages', to='app.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_3166_1', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_countries', to='app.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='app.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_3166_1', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_titles', to='app.Movie')),
            ],
        ),
    ]
