# Generated by Django 2.2.3 on 2019-07-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fetched',
            field=models.BooleanField(default=False),
        ),
    ]
