# Generated by Django 2.2.3 on 2019-07-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190716_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativetitle',
            name='iso_3166_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productioncountries',
            name='iso_3166_1',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='spokenlanguage',
            name='iso_639_1',
            field=models.CharField(max_length=4),
        ),
    ]
