# Generated by Django 2.2.3 on 2019-07-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190718_0554'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['id'], name='movie_pk_index'),
        ),
    ]
