# Generated by Django 2.2.3 on 2019-07-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_genre_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='movies',
            field=models.ManyToManyField(related_name='genres', to='app.Movie'),
        ),
        migrations.AddField(
            model_name='productioncountries',
            name='movies',
            field=models.ManyToManyField(related_name='production_countries2', to='app.Movie'),
        ),
        migrations.AddField(
            model_name='spokenlanguage',
            name='movies',
            field=models.ManyToManyField(related_name='spoken_languages2', to='app.Movie'),
        ),
    ]
