# Generated by Django 2.2.3 on 2019-07-20 11:07

from django.db import models, migrations


def migrate_spoken_languages(apps, schema_editor):
    SpokenLanguages = apps.get_model('app', 'SpokenLanguage')

    for spokenLanguage in SpokenLanguages.objects.all():
        spokenLanguage.movies.add(spokenLanguage.movie)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_migrate_production_countries'),
    ]

    operations = [
        migrations.RunPython(migrate_spoken_languages),
    ]
