# Generated by Django 2.2.3 on 2019-07-20 11:07

from django.db import models, migrations


def migrate_production_countries(apps, schema_editor):
    Movie = apps.get_model('app', 'Movie')
    ProductionCountries = apps.get_model('app', 'ProductionCountries')

    # Avatar
    #   USA
    #   AU
    # Shawshank
    #   USA

    for movie in Movie.objects.filter(fetched=True).all():
        for country in movie.production_countries.all():
            try:
                prod_country = ProductionCountries.objects.get(iso_3166_1=country.iso_3166_1)
                print("Found: %s" % prod_country.name)
            except Exception as exc:
                prod_country = country
                print("Did not find %s" % country.name)
            movie.production_countries2.add(prod_country)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190720_1305'),
    ]

    operations = [
        migrations.RunPython(migrate_production_countries),
    ]
