# Generated by Django 2.2.3 on 2019-07-20 11:07

from django.db import models, migrations


def migrate_production_countries(apps, schema_editor):
    ProductionCountries = apps.get_model('app', 'ProductionCountries')

    for productionCountry in ProductionCountries.objects.all():
        productionCountry.movies.add(productionCountry.movie)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190720_1305'),
    ]

    operations = [
        migrations.RunPython(migrate_production_countries),
    ]
