# Generated by Django 2.2.3 on 2019-07-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_migrate_spoken_languages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.RemoveField(
            model_name='productioncountries',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='spokenlanguage',
            name='movie',
        ),
        migrations.AlterField(
            model_name='productioncountries',
            name='movies',
            field=models.ManyToManyField(related_name='production_countries', to='app.Movie'),
        ),
        migrations.AlterField(
            model_name='spokenlanguage',
            name='movies',
            field=models.ManyToManyField(related_name='spoken_languages', to='app.Movie'),
        ),
    ]
