# Generated by Django 2.2.3 on 2019-07-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_migrate_spoken_languages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.RemoveField(
            model_name='productioncountries',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productioncountries',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='spokenlanguage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='spokenlanguage',
            name='movie',
        ),
        migrations.AlterField(
            model_name='productioncountries',
            name='iso_3166_1',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spokenlanguage',
            name='iso_639_1',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
