# Generated by Django 2.2.3 on 2019-07-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190720_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncountries',
            name='movies',
            field=models.ManyToManyField(related_name='production_countries', to='app.Movie'),
        ),
        migrations.AlterField(
            model_name='spokenlanguage',
            name='movies',
            field=models.ManyToManyField(related_name='spoken_languages', to='app.Movie'),
        ),
    ]
