# Generated by Django 2.2.3 on 2019-08-14 16:26
import json, ast
from django.db import models, migrations, connection


def add_genres_from_raw_response(apps, schema_editor):
    Movie = apps.get_model('app', 'Movie')
    Genres = apps.get_model('app', 'Genre')

    for movie in Movie.objects.filter(fetched=True).all():
        genres_from_movie = ast.literal_eval(movie.raw_response)["genres"]
        for genre in genres_from_movie:
            movie.genres.add(Genres.objects.filter(id=genre["id"]).first())


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190803_2150'),
    ]

    operations = [
        migrations.RunPython(add_genres_from_raw_response),
    ]
