# Generated by Django 4.1.5 on 2023-01-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_alternativetitle_iso_3166_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativetitle',
            name='iso_3166_1',
            field=models.CharField(max_length=50),
        ),
    ]
