# Generated by Django 4.1.5 on 2023-01-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_alternativetitle_iso_3166_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativetitle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productioncountries',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spokenlanguage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
